apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: coffee
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30300
  selector:
    app: grafana
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: coffee
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:5.4.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP